### ISSUE TITLE
A and B matrices?

### ISSUE THREAD

**Issue by YumingChennn** [aftersomemath/mujoco_python_viewer_examples#1]
Excuse me. I have already reviewed your code. Could I ask you a question? How did you get the A and B matrices in the double pendulum python project?

**Comment by aftersomemath** [comment]
A, B in the double pendulum example were estimated with the `derivative` sample code that used to be distributed with MuJoCo. The `derivative` sample was replaced with the `mjd_transitionFD` function.

In a minute, I will push code that uses `mjd_transitionFD` to estimate A, B for the double pendulum automatically. The results are almost identical. With this change the approach is almost the same as LQR tutorial mentioned in MuJoCo's README.

**Comment by YumingChennn** [comment]
First of all, I really appreciate your response to my question; your method is indeed quite clever. Now that I know you're using mjd_transitionFD to obtain the positive values ​​of A and B matrices, I couldn't get the same values ​​based on this method with your double pendulum file. If you don't mind, could you share your code or process?

I also wanted to ask how you decide the order of the values ​​inside x? Because many people calculate LQR in the order of position, velocity, angle, and angular acceleration, but it seems like you're not following this arrangement.
```
x = np.concatenate((
        d.joint('shoulder').qpos,
        d.joint('elbow').qpos,
        d.joint('shoulder').qvel,
        d.joint('elbow').qvel))

```

**Comment by aftersomemath** [comment]
The code I pushed earlier today as an [update to `double_pendulum.py`](https://github.com/aftersomemath/mujoco_python_viewer_examples/commit/2009e9881b2fc2dad8a7c8bbba0789df08131513) includes all the code to estimate of A,B from m, d using `mjd_transitionFD`.

The state vector's element order is determined by MuJoCo. MuJoCo uses generalized coordinates for state in the order position, velocity, actuator activation as explained [here](https://mujoco.readthedocs.io/en/stable/computation/index.html#gephysicsstate). In this case there is no actuator activation state and I happen to know that the shoulder joint is the first state and the elbow is the second.

**Comment by YumingChennn** [comment]
Thank you so much for answering my question, which saved me weeks of time. Wishing you all the best for a safe and smooth journey ahead.
